version: "3"

services:
  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ' --appendonly yes'    
  mongo:
    image: mongo:3.6.2
    volumes:
      - mongo-data:/data/db
    ports: 
      - 27017:27017

volumes:
  redis-data:
  mongo-data:       
      