version: "3"

services:
  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ' --appendonly yes'    
  mongo:
    image: mongo:3.6.3
    volumes:
      - mongo-data:/data/db
    ports: 
      - 27017:27017
  postgres:
    image: postgres:10.12
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - pg-data:/var/lib/postgresql/data  
  mysql:
    image: mysql:8.0.20
    ports:
      - 3306:3306 
    environment:  
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql  
     

volumes:
  redis-data:
  mongo-data:
  pg-data:
  mysql-data:       
      